# Site settings
title: Sam Rubin | Web Developer
description: "The personal and professional website of Sam Rubin, a front end web developer located in Arlington, Virginia."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samrubin.co" # the base hostname & protocol for your site
keywords: "rubin, sam, Sam Rubin, arlington, developer, web, designer, front end, web design, development, front-end developer, virginia, freelance, freelance developer, deloitte"

collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project

exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Gems
gems: [jekyll-paginate]


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: false
permalink: /blog/:title
paginate: 6
paginate_path: '/blog/page:num/'

