# Site settings
title: Sam Rubin | Web Developer
description: "The personal and professional website of Sam Rubin, a front end web developer."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samrubin.co" # the base hostname & protocol for your site

collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project

exclude:
  - package.json
  - node_modules
  - gulpfile.js


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: false
permalink: /blog/:title

